version: '3.9'

services:
  www:
    build: .
    ports: 
      - 8080:80
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - default

  db:
    image: mysql:8.0.41
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: escuela
      MYSQL_USER: edgar
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - data:/var/lib/mysql
      - ./backend/db/escuela.sql:/docker-entrypoint-initdb.d/escuela.sql
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8000:80
    environment:
      PMA_HOST: db
      MYSQL_USER: edgar
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
    depends_on:
      - db
    networks:
      - default

volumes:
  data:
